// <auto-generated />
namespace WebDev3.CentiSoft.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class bias : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bias));
        
        string IMigrationMetadata.Id
        {
            get { return "201803020956163_bias"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
